[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"
url = "http://example.com"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[[reducers]]
type = "PointByTx"
key_prefix = "c1"

[[reducers]]
type = "PoolByStake"
key_prefix = "c2"

[[reducers]]
type = "AddressByTxo"
key_prefix = "c3"

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[intersect]
type = "Origin"

[chain]
type = "mainnet"

[policy]
missing_data = "Skip"

