services:
  alice:
    build: ./
    command: >
      /aya/target/release/aya-node --dev --tmp --alice --port 30333 --rpc-port 9944
      --unsafe-rpc-external
      --rpc-cors all --validator
    
    ports:
      - "30333:30333"
   
      - "9944:9944"
    networks:
      - aya_network

  bob:
    build: ./
    environment:
      - NODE_KEY=${NODE_KEY}
      - ALICE_IP=${ALICE_IP}
    command: >
      /aya/target/release/aya-node --dev --tmp --bob --port 30334 --rpc-port 9946
      --unsafe-rpc-external
      --rpc-cors all --validator --bootnodes /ip4/${ALICE_IP}/tcp/30333/p2p/${NODE_KEY}
    depends_on:
      - alice
    networks:
      - aya_network
    ports:
      - "30334:30334"
   
      - "9946:9946"
  cardano-node:
    image: cardanocommunity/cardano-node
    container_name: cardano-node
    volumes:
      - ./cardano-node-ipc:/ipc # socket path
      - ./cardano-node-data:/data
      #- ./configuration:/configuration
      - ./config:/config
      - ./cardano-wallet:/cardano-wallet # cardano-cli path
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI=/cardano-wallet/cardano-cli
      - TESTNET_MAGIC=1
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
      - NETWORK=preprod
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - aya_network
  
  
    
networks:
  aya_network:
    driver: bridge

