services:
  alice:
    build: ./
    command: >
      /aya/target/release/aya-node --dev --tmp --alice --port 30333 --rpc-port 9944
      --unsafe-rpc-external
      --rpc-cors all --validator
    
    ports:
      - "30333:30333"
   
      - "9944:9944"
    networks:
      - aya_network

  bob:
    build: ./
    environment:
      - NODE_KEY=${NODE_KEY}
      - ALICE_IP=${ALICE_IP}
    command: >
      /aya/target/release/aya-node --dev --tmp --bob --port 30334 --rpc-port 9946
      --unsafe-rpc-external
      --rpc-cors all --validator --bootnodes /ip4/${ALICE_IP}/tcp/30333/p2p/${NODE_KEY}
    depends_on:
      - alice
    networks:
      - aya_network
    ports:
      - "30334:30334"
   
      - "9946:9946"

  scrolls:
    image: sylvaincormier/chain-follower:v0.2
    command: ["/usr/bin/aya_chain_follower", "daemon", "--config", "/app/daemon_conf.toml"]
    environment:  
      - RUST_LOG=info
    volumes:
      - ./daemon_conf.toml:/app/daemon_conf.toml  
    ports:
      - "9615:9615"
    networks:
      - aya_network
    
networks:
  aya_network:
    driver: bridge

